name: Deploy
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      STAGE: qa
      REPOSITORY: https://github.com/${{ github.repository }}
      BRANCH: ${{ github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      SSM_PREFIX: saapless

    steps:
      - uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_DEVOPS_ROLE }}
          role-session-name: github
          role-skip-session-tagging: true

      - name: Deploy services
        run: npm run deploy

      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npm run test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 5

      - name: Remove services
        run: npm run remove
